### ISSUE TITLE
AESMD installed: false, why ?

### ISSUE THREAD

**Issue by quertenmont** [gramineproject/gsc#99]
Hello,

I am still having a hard time to make the attestation flow working on kubernetes on azure.
Since last time, I am able to deploy my sgx enabled container on azure aks and write to /dev/attestation/user_report_data

unfortunately, I get an error when doing so:

```
cat: /dev/attestation/quote: Permission denied
error: Cannot connect to aesm_service (tried sgx_aesm_socket_base and /var/run/aesmd/aesm.socket UNIX sockets).
Please check its status! (`service aesmd status` on Ubuntu)
error: Failed to get quote
```

I check out what is my system status with "is-sgx-available"
and here is what I get:
```
SGX supported by CPU: true
SGX1 (ECREATE, EENTER, ...): true
SGX2 (EAUG, EACCEPT, EMODPR, ...): true
Flexible Launch Control (IA32_SGXPUBKEYHASH{0..3} MSRs): true
SGX extensions for virtualizers (EINCVIRTCHILD, EDECVIRTCHILD, ESETCONTEXT): false
Extensions for concurrent memory management (ETRACKC, ELDBC, ELDUC, ERDINFO): false
CET enclave attributes support (See Table 37-5 in the SDM): false
Key separation and sharing (KSS) support (CONFIGID, CONFIGSVN, ISVEXTPRODID, ISVFAMILYID report fields): true
Max enclave size (32-bit): 0x80000000
Max enclave size (64-bit): 0x100000000000000
EPC size: 0x200000000
SGX driver loaded: false
AESMD installed: false
SGX PSW/libsgx installed: false
```

For deploying my container to kubernetes I followed the recommendation provided by azure doc:
https://learn.microsoft.com/en-us/azure/confidential-computing/confidential-nodes-aks-addon
including the mounting of the /var/run/aesmd/ volume

my configuration is here:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dv-algo
  namespace: app-db9fbac56e14
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dv-algo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        algo-sandboxed: "false"
        app: dv-algo
    spec:
      containers:
      - env:
        - name: SGX_AESM_ADDR
          value: "1"
        image: dvaks.azurecr.io/gsc-dv-algo:db9fbac56e14-221005122423
        imagePullPolicy: Always
        name: main
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
            sgx.intel.com/epc: 2Gi
          requests:
            cpu: 50m
            memory: 1Gi
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
        - mountPath: /var/run/aesmd
          name: var-run-aesmd
      volumes:
      - emptyDir: {}
        name: cache-volume
      - hostPath:
          path: /var/run/aesmd
          type: ""
        name: var-run-aesmd
```

At this point any help would be very useful.

Thanks in advance
Loic

**Comment by mythi** [comment]
> At this point any help would be very useful.

Did you setup the cluster using `--enable-sgxquotehelper`? With that you should see the AESMD pod running (IIRC it's called `sgx-helper` or something, check `kubectl get pods -A | grep sgx´).

**Comment by quertenmont** [comment]
Sure, I did
```
> kubectl get pods -A | grep sgx
kube-system        sgx-plugin-2cnf7                                     1/1     Running   0             9d
kube-system        sgx-webhook-84778cc7d7-kdbgf                         1/1     Running   0             90d
```
otherwise, my gsc-fied container would not event start I believe

Also if it helps, I am building my gsc image with this manifest:
```
Distro: "ubuntu:20.04"

Registry: ""
Gramine:
    Repository: "https://github.com/gramineproject/gramine.git"
    Branch:     "v1.2"
SGXDriver:
    Repository: "https://github.com/intel/SGXDataCenterAttestationPrimitives.git"
    Branch:     "DCAP_1.11 && cp -r driver/linux/* ."
```

**Comment by dimakuv** [comment]
@quertenmont I hope that @mythi can help further with this, but from my side:

Seems like you can run arbitrary commands on the deployed machine, right (based on the fact that you showed us the result of `is-sgx-available`)? So, could you run `service aesmd status` on a deployed machine and show us the result?

**Comment by mythi** [comment]
@quertenmont I think you are missing the `sgx-quotehelper` so maybe [try this Azure command](https://learn.microsoft.com/en-us/azure/confidential-computing/confidential-nodes-aks-addon#sample-implementation):

```
az aks addon update --addon confcom --name " YourAKSClusterName " --resource-group "YourResourceGroup " --enable-sgxquotehelper
```

I just created a fresh AKS cluster and what I see is:

```
kube-system   sgx-plugin-2bc85                      1/1     Running   0          9m15s
kube-system   sgx-plugin-k6rzd                      1/1     Running   0          9m10s
kube-system   sgx-plugin-wmkl5                      1/1     Running   0          9m
kube-system   sgx-quote-helper-kp9pd                1/1     Running   0          9m
kube-system   sgx-quote-helper-l5v7c                1/1     Running   0          9m15s
kube-system   sgx-quote-helper-zpkwb                1/1     Running   0          9m10s
kube-system   sgx-webhook-75964f44c6-hx8w4          1/1     Running   0          14m
```

and with the following `.yaml`:
```
apiVersion: v1
kind: Pod
metadata:
  name: intelsgx-aesmd-test
spec:
  restartPolicy: Never
  containers:
    -
      name: intelsgx-container
      image: busybox
      imagePullPolicy: IfNotPresent
      args:
      - sleep
      - "1000000"
      securityContext:
        readOnlyRootFilesystem: true
        capabilities:
          add: ["IPC_LOCK"]
      resources:
        limits:
          sgx.intel.com/epc: 12Mi
      volumeMounts:
      - name: aesmd
        mountPath: /var/run/aesmd
  volumes:
  - name: aesmd
    hostPath:
      path: /var/run/aesmd
```

I can see:
```
$ kubectl exec -it intelsgx-aesmd-test -- ls /var/run/aesmd
aesm.socket
```
